/**
 * Clinical Disclaimer Service
 * Manages clinical disclaimers and therapist override requirements for AI insights
 * 
 * 🚨 CRITICAL SAFETY: All AI insights must include clinical disclaimers
 * and require therapist validation before display to clients.
 */

import { prisma } from '@/lib/prisma-optimized';
import { logger } from '@/lib/logger';

export interface ClinicalDisclaimer {
  id: string;
  version: string;
  content: string;
  requiresAcknowledgment: boolean;
  therapistOverrideRequired: boolean;
  severity: 'standard' | 'warning' | 'critical';
  validFrom: Date;
  validUntil?: Date;
  createdBy: string; // Therapist or admin ID
  lastUpdated: Date;
}

export interface DisclaimerAcknowledgment {
  userId: string;
  disclaimerId: string;
  acknowledgedAt: Date;
  ipAddress?: string;
  userAgent?: string;
  version: string;
}

export interface TherapistOverride {
  userId: string;
  insightId: string;
  therapistId: string;
  overrideReason: string;
  overrideType: 'approve' | 'modify' | 'reject';
  originalContent: string;
  modifiedContent?: string;
  overriddenAt: Date;
  expiresAt?: Date;
}

// Standard clinical disclaimers
const STANDARD_DISCLAIMERS: Omit<ClinicalDisclaimer, 'id' | 'createdBy' | 'lastUpdated'>[] = [
  {
    version: '1.0.0',
    content: 'AI insights are for informational purposes only and do not constitute professional medical or psychological advice. These insights are generated by artificial intelligence and require validation by a licensed therapist before implementation.',
    requiresAcknowledgment: true,
    therapistOverrideRequired: true,
    severity: 'standard',
    validFrom: new Date('2025-01-01'),
  },
  {
    version: '1.0.0',
    content: 'WARNING: AI-generated relationship insights may not accurately reflect your specific situation. All therapeutic recommendations must be reviewed and approved by your licensed therapist before taking action.',
    requiresAcknowledgment: true,
    therapistOverrideRequired: true,
    severity: 'warning',
    validFrom: new Date('2025-01-01'),
  },
  {
    version: '1.0.0',
    content: 'CRITICAL: This AI system is NOT HIPAA COMPLIANT and should not be used for clinical decision-making. If you are experiencing a mental health crisis, contact your therapist immediately or call emergency services.',
    requiresAcknowledgment: true,
    therapistOverrideRequired: true,
    severity: 'critical',
    validFrom: new Date('2025-01-01'),
  }
];

export class ClinicalDisclaimerService {
  private static instance: ClinicalDisclaimerService;

  private constructor() {}

  public static getInstance(): ClinicalDisclaimerService {
    if (!ClinicalDisclaimerService.instance) {
      ClinicalDisclaimerService.instance = new ClinicalDisclaimerService();
    }
    return ClinicalDisclaimerService.instance;
  }

  /**
   * Get appropriate disclaimer for insight type and severity
   */
  async getRequiredDisclaimer(
    insightType: string,
    severity: 'low' | 'medium' | 'high' = 'medium'
  ): Promise<ClinicalDisclaimer> {
    try {
      // Map severity to disclaimer severity
      let disclaimerSeverity: ClinicalDisclaimer['severity'] = 'standard';
      if (severity === 'high') disclaimerSeverity = 'warning';
      
      // Get active disclaimer of appropriate severity
      const disclaimer = await this.getActiveDisclaimer(disclaimerSeverity);
      
      if (!disclaimer) {
        logger.warn('No active disclaimer found, using fallback', { 
          insightType, 
          severity 
        });
        return this.getFallbackDisclaimer();
      }

      return disclaimer;

    } catch (error) {
      logger.error('Failed to get required disclaimer', {
        insightType,
        severity,
        error: error instanceof Error ? error.message : error
      });
      return this.getFallbackDisclaimer();
    }
  }

  /**
   * Check if user has acknowledged required disclaimers
   */
  async hasUserAcknowledgedDisclaimers(
    userId: string,
    requiredDisclaimerIds: string[]
  ): Promise<boolean> {
    try {
      for (const disclaimerId of requiredDisclaimerIds) {
        const acknowledgment = await this.getUserAcknowledgment(userId, disclaimerId);
        if (!acknowledgment) {
          return false;
        }
        
        // Check if acknowledgment is still valid (not expired)
        const disclaimer = await this.getDisclaimerById(disclaimerId);
        if (disclaimer?.validUntil && new Date() > disclaimer.validUntil) {
          return false;
        }
      }
      
      return true;

    } catch (error) {
      logger.error('Failed to check disclaimer acknowledgments', {
        userId,
        requiredDisclaimerIds,
        error: error instanceof Error ? error.message : error
      });
      return false; // Fail secure - require acknowledgment
    }
  }

  /**
   * Record user acknowledgment of disclaimer
   */
  async recordAcknowledgment(
    userId: string,
    disclaimerId: string,
    metadata?: {
      ipAddress?: string;
      userAgent?: string;
    }
  ): Promise<void> {
    try {
      const disclaimer = await this.getDisclaimerById(disclaimerId);
      if (!disclaimer) {
        throw new Error(`Disclaimer ${disclaimerId} not found`);
      }

      // Check if already acknowledged
      const existing = await this.getUserAcknowledgment(userId, disclaimerId);
      if (existing) {
        logger.info('User already acknowledged disclaimer', { userId, disclaimerId });
        return;
      }

      // Record new acknowledgment
      // This would be stored in database
      logger.info('Recorded disclaimer acknowledgment', {
        userId,
        disclaimerId,
        version: disclaimer.version,
        acknowledgedAt: new Date()
      });

    } catch (error) {
      logger.error('Failed to record disclaimer acknowledgment', {
        userId,
        disclaimerId,
        error: error instanceof Error ? error.message : error
      });
      throw error;
    }
  }

  /**
   * Check if therapist override is required for insight
   */
  async requiresTherapistOverride(
    insightType: string,
    confidenceLevel: number,
    severity: 'low' | 'medium' | 'high'
  ): Promise<boolean> {
    // ALWAYS require therapist override for safety
    return true;
  }

  /**
   * Record therapist override decision
   */
  async recordTherapistOverride(
    override: Omit<TherapistOverride, 'overriddenAt'>
  ): Promise<void> {
    try {
      const completeOverride: TherapistOverride = {
        ...override,
        overriddenAt: new Date()
      };

      // This would be stored in database
      logger.info('Recorded therapist override', {
        userId: override.userId,
        insightId: override.insightId,
        therapistId: override.therapistId,
        overrideType: override.overrideType
      });

    } catch (error) {
      logger.error('Failed to record therapist override', {
        override,
        error: error instanceof Error ? error.message : error
      });
      throw error;
    }
  }

  /**
   * Get therapist override for insight
   */
  async getTherapistOverride(
    userId: string,
    insightId: string
  ): Promise<TherapistOverride | null> {
    try {
      // This would query database for override
      return null; // No override found

    } catch (error) {
      logger.error('Failed to get therapist override', {
        userId,
        insightId,
        error: error instanceof Error ? error.message : error
      });
      return null;
    }
  }

  /**
   * Check if insight can be displayed to user
   */
  async canDisplayInsight(
    userId: string,
    insightId: string,
    insightType: string,
    severity: 'low' | 'medium' | 'high' = 'medium'
  ): Promise<{
    canDisplay: boolean;
    reason?: string;
    requiredActions?: string[];
  }> {
    try {
      // 1. Check therapist override requirement
      const requiresOverride = await this.requiresTherapistOverride(
        insightType, 
        0, // confidence doesn't matter - always require override
        severity
      );

      if (requiresOverride) {
        const override = await this.getTherapistOverride(userId, insightId);
        if (!override || override.overrideType !== 'approve') {
          return {
            canDisplay: false,
            reason: 'Requires therapist approval',
            requiredActions: ['Therapist must review and approve insight']
          };
        }

        // Check if override has expired
        if (override.expiresAt && new Date() > override.expiresAt) {
          return {
            canDisplay: false,
            reason: 'Therapist approval expired',
            requiredActions: ['Therapist must re-approve insight']
          };
        }
      }

      // 2. Check disclaimer acknowledgment
      const disclaimer = await this.getRequiredDisclaimer(insightType, severity);
      if (disclaimer.requiresAcknowledgment) {
        const acknowledged = await this.hasUserAcknowledgedDisclaimers(
          userId, 
          [disclaimer.id]
        );
        
        if (!acknowledged) {
          return {
            canDisplay: false,
            reason: 'Disclaimer not acknowledged',
            requiredActions: ['User must acknowledge clinical disclaimer']
          };
        }
      }

      return { canDisplay: true };

    } catch (error) {
      logger.error('Failed to check if insight can be displayed', {
        userId,
        insightId,
        insightType,
        severity,
        error: error instanceof Error ? error.message : error
      });
      
      // Fail secure - don't display if check fails
      return {
        canDisplay: false,
        reason: 'Safety check failed',
        requiredActions: ['System error - contact support']
      };
    }
  }

  /**
   * Initialize standard disclaimers in database
   */
  async initializeStandardDisclaimers(createdBy: string): Promise<void> {
    try {
      for (const disclaimerData of STANDARD_DISCLAIMERS) {
        // Check if disclaimer already exists
        const existing = await this.getActiveDisclaimer(disclaimerData.severity);
        if (existing) {
          logger.info('Standard disclaimer already exists', { 
            severity: disclaimerData.severity 
          });
          continue;
        }

        // Create new disclaimer
        const disclaimer: ClinicalDisclaimer = {
          id: `disclaimer_${disclaimerData.severity}_${Date.now()}`,
          ...disclaimerData,
          createdBy,
          lastUpdated: new Date()
        };

        // This would be stored in database
        logger.info('Created standard disclaimer', {
          id: disclaimer.id,
          severity: disclaimer.severity,
          version: disclaimer.version
        });
      }

    } catch (error) {
      logger.error('Failed to initialize standard disclaimers', {
        createdBy,
        error: error instanceof Error ? error.message : error
      });
      throw error;
    }
  }

  // Private helper methods
  private async getActiveDisclaimer(
    severity: ClinicalDisclaimer['severity']
  ): Promise<ClinicalDisclaimer | null> {
    // This would query database for active disclaimer
    // For now, return fallback
    return this.getFallbackDisclaimer();
  }

  private async getDisclaimerById(disclaimerId: string): Promise<ClinicalDisclaimer | null> {
    // This would query database
    return null;
  }

  private async getUserAcknowledgment(
    userId: string, 
    disclaimerId: string
  ): Promise<DisclaimerAcknowledgment | null> {
    // This would query database
    return null;
  }

  private getFallbackDisclaimer(): ClinicalDisclaimer {
    return {
      id: 'fallback_disclaimer',
      version: '1.0.0',
      content: 'AI insights are for informational purposes only and do not replace professional therapy. All insights require therapist validation.',
      requiresAcknowledgment: true,
      therapistOverrideRequired: true,
      severity: 'warning',
      validFrom: new Date(),
      createdBy: 'system',
      lastUpdated: new Date()
    };
  }
}

/**
 * Utility function to get disclaimer service instance
 */
export function getDisclaimerService(): ClinicalDisclaimerService {
  return ClinicalDisclaimerService.getInstance();
}

/**
 * Middleware wrapper to check disclaimers before serving insights
 */
export async function withDisclaimerCheck<T>(
  userId: string,
  insightId: string,
  insightType: string,
  severity: 'low' | 'medium' | 'high',
  operation: () => Promise<T>
): Promise<{
  success: boolean;
  data?: T;
  disclaimer?: ClinicalDisclaimer;
  blockedReason?: string;
  requiredActions?: string[];
}> {
  const disclaimerService = getDisclaimerService();
  
  try {
    // Check if insight can be displayed
    const canDisplay = await disclaimerService.canDisplayInsight(
      userId,
      insightId,
      insightType,
      severity
    );

    if (!canDisplay.canDisplay) {
      const disclaimer = await disclaimerService.getRequiredDisclaimer(
        insightType, 
        severity
      );
      
      return {
        success: false,
        disclaimer,
        blockedReason: canDisplay.reason,
        requiredActions: canDisplay.requiredActions
      };
    }

    // Execute operation if checks pass
    const data = await operation();
    
    return {
      success: true,
      data
    };

  } catch (error) {
    logger.error('Disclaimer check failed', {
      userId,
      insightId,
      insightType,
      severity,
      error: error instanceof Error ? error.message : error
    });
    
    return {
      success: false,
      blockedReason: 'Safety check failed',
      requiredActions: ['Contact support']
    };
  }
}

/**
 * Emergency override for crisis situations (therapist only)
 */
export async function emergencyOverride(
  therapistId: string,
  userId: string,
  reason: string,
  validationCode: string
): Promise<boolean> {
  // This would validate therapist credentials and emergency code
  // Only for genuine crisis situations where immediate access is needed
  
  logger.warn('EMERGENCY OVERRIDE ATTEMPTED', {
    therapistId,
    userId,
    reason,
    timestamp: new Date().toISOString(),
    requiresAudit: true
  });
  
  // For now, deny all emergency overrides - require proper approval process
  return false;
}