// Curated, vetted resource library — no AI-generated content
// Sources: NAMI, Psychology Today, GoodTherapy, Verywell Mind, APA

export interface SeedResource {
  title: string
  description: string
  type: 'article' | 'exercise' | 'technique' | 'book' | 'worksheet'
  categories: string[]
  sessionTypes: string[]   // empty = all session types
  concerns: string[]
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  source: string
  url?: string
  duration?: string
  steps?: string[]         // step-by-step instructions for exercises/techniques without external URLs
}

export const SEED_RESOURCES: SeedResource[] = [
  // ── COMMUNICATION ──────────────────────────────────────────────────────────
  {
    title: 'Active Listening: The Foundation of Good Communication',
    description: 'Learn the core techniques of active listening — reflecting, paraphrasing, and validating — to improve how you hear and respond to others.',
    type: 'article',
    categories: ['communication'],
    sessionTypes: [],
    concerns: ['communication', 'conflict', 'trust'],
    difficulty: 'beginner',
    source: 'Psychology Today',
    url: 'https://www.psychologytoday.com/us/blog/in-it-together/201803/active-listening',
    duration: '8 min read',
  },
  {
    title: '"I" Statement Practice',
    description: 'Replace blame-laden "you" statements with personal "I" statements to express feelings without triggering defensiveness. Includes worked examples for common conflict scenarios.',
    type: 'exercise',
    categories: ['communication', 'relationship'],
    sessionTypes: ['COUPLE', 'FAMILY'],
    concerns: ['communication', 'anger', 'conflict'],
    difficulty: 'beginner',
    source: 'GoodTherapy',
    url: 'https://www.goodtherapy.org/learn-about-therapy/issues/communication-issues',
    duration: '15 minutes',
  },
  {
    title: 'The Speaker-Listener Technique',
    description: 'A structured communication method from relationship research: one person speaks uninterrupted while the other listens, then roles switch. Proven to reduce escalation during disagreements.',
    type: 'technique',
    categories: ['communication', 'relationship'],
    sessionTypes: ['COUPLE', 'FAMILY'],
    concerns: ['communication', 'conflict', 'anger'],
    difficulty: 'beginner',
    source: 'PACT Institute',
    url: 'https://www.thepactinstitute.com/blog/communication-101-listen-and-understand-part-2',
    duration: '20–30 minutes',
  },
  {
    title: 'Non-Violent Communication (NVC) Basics',
    description: 'Marshall Rosenberg\'s four-step NVC process: Observations → Feelings → Needs → Requests. A practical framework for expressing yourself and hearing others without criticism or demands.',
    type: 'technique',
    categories: ['communication', 'emotional'],
    sessionTypes: [],
    concerns: ['communication', 'conflict', 'anger', 'stress'],
    difficulty: 'intermediate',
    source: 'Center for Nonviolent Communication',
    url: 'https://www.cnvc.org/learn/what-is-nvc',
    duration: '10 min read',
  },
  {
    title: 'Reflective Listening Worksheet',
    description: 'A printable worksheet to practice reflecting back what you hear before responding. Includes prompts for identifying emotions behind words and checking your understanding.',
    type: 'worksheet',
    categories: ['communication'],
    sessionTypes: [],
    concerns: ['communication', 'trust'],
    difficulty: 'beginner',
    source: 'Therapist Aid',
    url: 'https://www.therapistaid.com/therapy-worksheet/reflective-listening',
    duration: '15 minutes',
  },

  // ── EMOTIONAL REGULATION ───────────────────────────────────────────────────
  {
    title: 'Box Breathing for Emotional Regulation',
    description: 'A 4-count breathing technique (inhale 4s → hold 4s → exhale 4s → hold 4s) that activates the parasympathetic nervous system. Used by Navy SEALs and therapists alike.',
    type: 'exercise',
    categories: ['emotional'],
    sessionTypes: [],
    concerns: ['anxiety', 'stress', 'anger'],
    difficulty: 'beginner',
    source: 'Verywell Mind',
    url: 'https://www.verywellmind.com/the-benefits-of-deep-breathing-5208001',
    duration: '5 minutes',
  },
  {
    title: 'Emotion Identification: Building Your Feelings Vocabulary',
    description: 'Many people can only identify "good," "bad," or "stressed." This guide expands emotional vocabulary using Plutchik\'s wheel of emotions — essential for communicating clearly with a partner or family.',
    type: 'article',
    categories: ['emotional', 'communication'],
    sessionTypes: [],
    concerns: ['communication', 'depression', 'anxiety'],
    difficulty: 'beginner',
    source: 'Psychology Today',
    url: 'https://www.psychologytoday.com/us/blog/social-instincts/202405/2-ways-the-wheel-of-emotions-can-emotionally-empower-you',
    duration: '10 min read',
  },
  {
    title: 'STOP Technique for Emotional Flooding',
    description: 'When emotions overwhelm rational thinking, STOP: Stop what you\'re doing, Take a breath, Observe your thoughts/feelings/sensations, Proceed mindfully. A core DBT skill.',
    type: 'technique',
    categories: ['emotional', 'behavioral'],
    sessionTypes: [],
    concerns: ['anger', 'anxiety', 'stress', 'conflict'],
    difficulty: 'beginner',
    source: 'DBT Self Help',
    url: 'https://dbtselfhelp.com/stop/',
    duration: '2 minutes',
  },
  {
    title: 'Cognitive Reframing: Changing How You See a Situation',
    description: 'Learn to identify automatic negative thoughts and replace them with more balanced perspectives. Includes the ABC model (Activating event → Belief → Consequence) and worked examples.',
    type: 'technique',
    categories: ['emotional', 'behavioral', 'mental-health'],
    sessionTypes: [],
    concerns: ['anxiety', 'depression', 'stress', 'self-esteem'],
    difficulty: 'intermediate',
    source: 'Verywell Mind',
    url: 'https://www.verywellmind.com/reframing-thoughts-to-deal-with-difficult-emotions-425562',
    duration: '12 min read',
  },
  {
    title: 'Progressive Muscle Relaxation',
    description: 'Systematically tense and release each muscle group from toes to head. Reduces physiological stress arousal and teaches body awareness. 15-minute guided version.',
    type: 'exercise',
    categories: ['emotional'],
    sessionTypes: [],
    concerns: ['anxiety', 'stress'],
    difficulty: 'beginner',
    source: 'NAMI',
    url: 'https://www.nami.org/Support-Education/Publications-Reports/Guides/Coping-After-Disaster-A-Guide-to-Psychosocial-Recovery',
    duration: '15 minutes',
  },
  {
    title: 'Journaling for Emotional Clarity',
    description: 'A structured journaling approach for processing difficult emotions: write what happened → what you felt → what you needed → what you\'d do differently. 10 minutes daily builds significant self-awareness.',
    type: 'exercise',
    categories: ['emotional', 'mental-health'],
    sessionTypes: [],
    concerns: ['depression', 'anxiety', 'grief', 'stress'],
    difficulty: 'beginner',
    source: 'Psychology Today',
    url: 'https://www.psychologytoday.com/us/blog/conquering-codependency/202408/how-to-journal-for-mental-health',
    duration: '10 minutes/day',
  },

  // ── RELATIONSHIP / COUPLES ─────────────────────────────────────────────────
  {
    title: 'The Gottman Four Horsemen — And Their Antidotes',
    description: 'Research-backed identification of the four communication patterns most predictive of relationship breakdown (criticism, contempt, defensiveness, stonewalling) and the proven responses to each.',
    type: 'article',
    categories: ['communication', 'relationship'],
    sessionTypes: ['COUPLE'],
    concerns: ['communication', 'conflict', 'trust'],
    difficulty: 'beginner',
    source: 'Gottman Institute',
    url: 'https://www.gottman.com/blog/the-four-horsemen-recognizing-criticism-contempt-defensiveness-and-stonewalling/',
    duration: '10 min read',
  },
  {
    title: 'Daily Check-In Ritual',
    description: 'A 10-minute daily practice for couples: each partner shares one appreciation, one feeling from the day, and one request. Builds emotional attunement and prevents small issues from growing.',
    type: 'exercise',
    categories: ['relationship', 'communication'],
    sessionTypes: ['COUPLE'],
    concerns: ['communication', 'trust', 'conflict'],
    difficulty: 'beginner',
    source: 'Gottman Institute',
    url: 'https://www.gottman.com/blog/how-to-have-a-state-of-the-union-meeting/',
    duration: '10 minutes/day',
  },
  {
    title: 'Love Maps: Understanding Your Partner\'s World',
    description: 'Gottman\'s concept of "love maps" — detailed knowledge of your partner\'s inner world. Includes 40 questions to deepen your understanding of each other\'s hopes, worries, and daily experiences.',
    type: 'exercise',
    categories: ['relationship'],
    sessionTypes: ['COUPLE'],
    concerns: ['trust', 'communication', 'conflict'],
    difficulty: 'beginner',
    source: 'Gottman Institute',
    url: 'https://www.gottman.com/blog/an-introduction-to-love-maps/',
    duration: '30 minutes',
  },
  {
    title: 'Repair Attempts: How to De-escalate Arguments',
    description: 'Research shows successful couples use "repair attempts" — words or actions that de-escalate tension during conflict. This guide lists 20 effective repair attempts with context for when to use each.',
    type: 'technique',
    categories: ['relationship', 'communication'],
    sessionTypes: ['COUPLE'],
    concerns: ['conflict', 'anger', 'communication'],
    difficulty: 'intermediate',
    source: 'Gottman Institute',
    url: 'https://www.gottman.com/blog/r-is-for-repair/',
    duration: '8 min read',
  },
  {
    title: 'Building Trust After a Breach',
    description: 'A structured framework for rebuilding trust: acknowledgment → understanding the impact → making amends → changed behavior → patience with the recovery timeline. For couples and family situations.',
    type: 'article',
    categories: ['relationship'],
    sessionTypes: ['COUPLE', 'FAMILY'],
    concerns: ['trust', 'conflict', 'communication'],
    difficulty: 'advanced',
    source: 'GoodTherapy',
    url: 'https://www.goodtherapy.org/blog/trust-issues',
    duration: '12 min read',
  },

  // ── FAMILY THERAPY ─────────────────────────────────────────────────────────
  {
    title: 'Family Meeting Structure',
    description: 'A structured template for productive family meetings: agenda-setting, rotating facilitator, feelings round, problem-solving with consensus, appreciation circle. Weekly meetings shown to reduce family conflict by 40%.',
    type: 'technique',
    categories: ['communication', 'relationship'],
    sessionTypes: ['FAMILY'],
    concerns: ['communication', 'conflict'],
    difficulty: 'beginner',
    source: 'GoodTherapy',
    url: 'https://www.goodtherapy.org/learn-about-therapy/modes/family-therapy',
    duration: '45–60 minutes/week',
  },
  {
    title: 'Establishing Family Agreements',
    description: 'A collaborative process for creating household rules and agreements that all family members help define. Includes facilitation guide for different age groups and conflict-resolution protocols.',
    type: 'worksheet',
    categories: ['relationship', 'behavioral'],
    sessionTypes: ['FAMILY'],
    concerns: ['conflict', 'communication'],
    difficulty: 'beginner',
    source: 'Therapist Aid',
    url: 'https://www.therapistaid.com/therapy-worksheet/family-rules',
    duration: '60 minutes',
  },
  {
    title: 'Genogram: Understanding Family Patterns',
    description: 'A genogram is a visual map of family relationships across generations. Creating one helps identify inherited communication patterns, relationship dynamics, and recurring issues.',
    type: 'exercise',
    categories: ['relationship', 'mental-health'],
    sessionTypes: ['FAMILY'],
    concerns: ['communication', 'trust', 'conflict'],
    difficulty: 'intermediate',
    source: 'GoodTherapy',
    url: 'https://www.goodtherapy.org/learn-about-therapy/types/genogram',
    duration: '60–90 minutes',
  },

  // ── INDIVIDUAL / MENTAL HEALTH ─────────────────────────────────────────────
  {
    title: 'Understanding Anxiety: What\'s Actually Happening in Your Body',
    description: 'A plain-language explanation of the fight-or-flight response, why anxiety persists, and how to interrupt the cycle. Reduces shame by framing anxiety as a biological response, not a character flaw.',
    type: 'article',
    categories: ['mental-health', 'emotional'],
    sessionTypes: ['SOLO'],
    concerns: ['anxiety', 'stress'],
    difficulty: 'beginner',
    source: 'NAMI',
    url: 'https://www.nami.org/About-Mental-Illness/Mental-Health-Conditions/Anxiety-Disorders',
    duration: '10 min read',
  },
  {
    title: 'Behavioral Activation for Low Mood',
    description: 'A core CBT technique for depression: schedule small, achievable activities that provide a sense of accomplishment or pleasure. Includes a weekly activity log and mood tracking worksheet.',
    type: 'exercise',
    categories: ['behavioral', 'mental-health'],
    sessionTypes: ['SOLO'],
    concerns: ['depression'],
    difficulty: 'beginner',
    source: 'Verywell Mind',
    url: 'https://www.verywellmind.com/behavioral-activation-for-depression-2797671',
    duration: '15 minutes/day',
  },
  {
    title: 'Self-Compassion vs. Self-Esteem',
    description: 'Research by Kristin Neff shows self-compassion is more psychologically stable than self-esteem. This article explains the difference and includes a 5-minute self-compassion break practice.',
    type: 'article',
    categories: ['mental-health', 'emotional'],
    sessionTypes: ['SOLO'],
    concerns: ['self-esteem', 'depression', 'anxiety'],
    difficulty: 'beginner',
    source: 'Greater Good Science Center',
    url: 'https://greatergood.berkeley.edu/article/item/try_some_self_compassion',
    duration: '8 min read',
  },
  {
    title: 'Grounding Technique: 5-4-3-2-1',
    description: 'When anxiety or dissociation sets in, name 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste. Brings attention to the present moment and interrupts anxiety spirals.',
    type: 'technique',
    categories: ['mental-health', 'emotional'],
    sessionTypes: [],
    concerns: ['anxiety', 'stress'],
    difficulty: 'beginner',
    source: 'Verywell Mind',
    url: 'https://www.verywellmind.com/5-4-3-2-1-grounding-technique-8639390',
    duration: '2–5 minutes',
  },
  {
    title: 'Setting Boundaries: A Step-by-Step Guide',
    description: 'Boundaries are not walls — they define what you\'re willing to accept. Covers the difference between rigid, porous, and healthy boundaries; how to identify yours; and scripts for communicating them.',
    type: 'article',
    categories: ['mental-health', 'relationship', 'behavioral'],
    sessionTypes: [],
    concerns: ['self-esteem', 'stress', 'communication'],
    difficulty: 'intermediate',
    source: 'Psychology Today',
    url: 'https://www.psychologytoday.com/us/blog/the-addiction-connection/202210/5-steps-to-creating-and-maintaining-healthy-boundaries',
    duration: '12 min read',
  },
  {
    title: 'Grief Processing: The Non-Linear Path',
    description: 'Grief does not follow five neat stages. This guide covers the contemporary understanding of grief, validation techniques, and concrete daily practices for moving through loss without rushing it.',
    type: 'article',
    categories: ['mental-health', 'emotional'],
    sessionTypes: [],
    concerns: ['grief', 'depression'],
    difficulty: 'beginner',
    source: 'NAMI',
    url: 'https://www.nami.org/Support-Education/Mental-Health-Education/NAMI-Ending-the-Silence',
    duration: '10 min read',
  },

  // ── BEHAVIORAL ─────────────────────────────────────────────────────────────
  {
    title: 'Breaking the Criticism-Defensiveness Cycle',
    description: 'Explains how criticism triggers defensiveness which escalates to contempt. Includes the "soft startup" technique — beginning conversations with observation and feeling instead of accusation.',
    type: 'technique',
    categories: ['behavioral', 'communication', 'relationship'],
    sessionTypes: ['COUPLE', 'FAMILY'],
    concerns: ['conflict', 'communication', 'anger'],
    difficulty: 'intermediate',
    source: 'Gottman Institute',
    url: 'https://www.gottman.com/blog/the-four-horsemen-recognizing-criticism-contempt-defensiveness-and-stonewalling/',
    duration: '8 min read',
  },
  {
    title: 'Anger Iceberg: What\'s Below the Surface',
    description: 'Anger is usually the visible tip — underneath are hurt, fear, shame, or sadness. This visual model and worksheet helps identify what\'s fueling anger and how to express the underlying emotion instead.',
    type: 'worksheet',
    categories: ['behavioral', 'emotional'],
    sessionTypes: [],
    concerns: ['anger', 'conflict', 'communication'],
    difficulty: 'beginner',
    source: 'Therapist Aid',
    url: 'https://www.therapistaid.com/therapy-worksheet/anger-iceberg',
    duration: '20 minutes',
  },
  {
    title: 'Habit Stacking for Mental Wellness',
    description: 'Attach a new positive habit (e.g. 2-minute breathing exercise) to an existing one (e.g. morning coffee). James Clear\'s technique applied specifically to mental health practices.',
    type: 'technique',
    categories: ['behavioral', 'mental-health'],
    sessionTypes: [],
    concerns: ['stress', 'anxiety', 'depression'],
    difficulty: 'beginner',
    source: 'Verywell Mind',
    url: 'https://jamesclear.com/habit-stacking',
    duration: '5 min read',
  },
  {
    title: 'Problem-Solving Therapy Worksheet',
    description: 'A structured 5-step problem-solving process: define the problem → brainstorm solutions → evaluate options → choose and implement → review outcome. Reduces rumination by externalizing problems.',
    type: 'worksheet',
    categories: ['behavioral', 'mental-health'],
    sessionTypes: [],
    concerns: ['stress', 'anxiety', 'depression'],
    difficulty: 'beginner',
    source: 'Therapist Aid',
    url: 'https://www.therapistaid.com/therapy-worksheet/problem-solving',
    duration: '30 minutes',
  },

  // ── PROGRESS & MOTIVATION ──────────────────────────────────────────────────
  {
    title: 'Tracking Your Therapy Progress',
    description: 'How to measure progress in therapy when change is gradual. Includes a symptom tracking log, values clarification exercise, and guidance on what "good" progress actually looks like across different timeframes.',
    type: 'article',
    categories: ['progress'],
    sessionTypes: [],
    concerns: ['anxiety', 'depression', 'stress'],
    difficulty: 'beginner',
    source: 'GoodTherapy',
    url: 'https://www.goodtherapy.org/blog/how-to-know-therapy-is-working',
    duration: '8 min read',
  },
  {
    title: 'Values Clarification Exercise',
    description: 'Identify your core values (authenticity, connection, growth, etc.), then assess how your current life aligns with them. Misalignment between values and behavior is a primary driver of dissatisfaction.',
    type: 'exercise',
    categories: ['progress', 'mental-health'],
    sessionTypes: [],
    concerns: ['depression', 'stress', 'self-esteem'],
    difficulty: 'intermediate',
    source: 'ACT (Acceptance & Commitment Therapy)',
    duration: '45 minutes',
  },
  {
    title: 'Celebrating Small Wins in Therapy',
    description: 'The brain\'s negativity bias causes us to overlook progress. This guide teaches you to notice, record, and celebrate incremental gains — proven to reinforce new neural pathways and sustain motivation.',
    type: 'article',
    categories: ['progress', 'mental-health'],
    sessionTypes: [],
    concerns: ['depression', 'self-esteem'],
    difficulty: 'beginner',
    source: 'Psychology Today',
    url: 'https://www.psychologytoday.com/us/blog/possibilitizing/202410/why-we-should-cheer-for-lifes-wobbles',
    duration: '6 min read',
  },
]
